# --- Azure Authentication ---
# Q1

"""
When running a Python script locally, DefaultAzureCredential relies on a specific 
ordered chain of lookup mechanisms to authenticate. In a local development context, 
it primarily searches for and utilizes the active security token and configuration 
profiles managed by the Azure CLI.

To enable this, you must have first executed the following command in your terminal:
    az login

DefaultAzureCredential automatically discovers this session by scanning standard, 
well-known local directory paths where the Azure CLI stores its authentication state 
and access tokens (such as the '.azure' folder located within the user's home directory). 
If it detects a valid, unexpired token generated by your terminal's 'az login' session, 
it seamlessly inherits those credentials to authorize the Python script's operations 
without requiring hardcoded passwords.
"""

# Q2

"""
A deployed production pipeline running on an Azure VM or container cannot use 
'az login' for authentication because 'az login' is an interactive command. It 
requires a human operator to physically open a web browser, select an account, 
and complete multi-factor authentication (MFA)—actions an automated, unattended 
cloud instance cannot perform.

Instead, a deployed application uses Managed Identities (or Service Principals). 
A Managed Identity is an automatically managed identity in Microsoft Entra ID 
assigned directly to the cloud resource (the VM or container host).

The exact same Python code works in both environments without any modifications 
because of the fallback design of DefaultAzureCredential. It executes an internal, 
prioritized checklist to find credentials:
1. It first looks for environment variables (Service Principals).
2. If absent, it checks if a Managed Identity endpoint is available (Production).
3. If that fails, it falls back to checking for local developer tools, including 
   the token cache created by 'az login' (Local Development).

Since the SDK dynamically probes the underlying hosting environment at runtime, the 
developer can write code once, test it locally using personal CLI credentials, and 
deploy it to production where it automatically upgrades to secure, role-based infrastructure access.
"""

# Q3

"""
An immediate 'AuthenticationError' when instantiating DefaultAzureCredential indicates 
that the credential chain completely ran out of options and could not find a single 
valid method to verify your identity. The two most likely causes are:

1. No Active Azure CLI Session (Local Context)
   - Cause: You either forgot to log in, your previous terminal session timed out, 
     or you are running the script in a terminal environment (like using 'sudo') 
     that doesn't have access to your normal user profile's Azure tokens.
   - Diagnosis: Run the command 'az account show' in your terminal. If it returns 
     an error stating that you are not logged in, or displays an unexpected account/
     subscription, your CLI session is the culprit. Fix it by running 'az login'.

2. Missing or Disabled Managed Identity (Production/Cloud Context)
   - Cause: The script is running on an Azure resource (like a VM or a container), 
     but "System-Assigned Managed Identity" was never enabled for that resource, 
     meaning the local metadata endpoint does not exist to provide credentials.
   - Diagnosis: If running in the cloud, check the Azure Portal, navigate to the specific 
     hosting resource, and look under the 'Identity' blade. Verify that the Status 
     is set to 'On'. If you are writing a script to check this programmatically, you 
     can check if the local environment variables or host endpoints return a 404/timeout 
     when probed by the SDK logs by enabling debug logging: 
     import logging; logging.basicConfig(level=logging.DEBUG)
"""

# --- Azure Blob Storage ---
# Q1

"""
The Azure Blob Storage hierarchy is organized into three distinct structural layers:

1. Storage Account: 
   The top-level container for all your Azure Storage resources. It provides a unique 
   namespace in Azure for your data and establishes the primary billing boundary, 
   access keys, and region location.
   
2. Container: 
   A nested grouping within the Storage Account, acting like a root directory. 
   Containers organize sets of blobs and allow you to apply shared access policies, 
   permissions, and metadata to everything inside them.
   
3. Blob: 
   The final, individual file layer. This is the actual raw data (such as a CSV file, 
   a JSON payload, an image, or a video) along with its associated metadata.

--- Concrete Analogy: A Corporate File Archiving System ---

- The Storage Account is the **Filing Building/Warehouse**. It represents the entire 
  physical property with its own secure street address, gate security, and utility bills. 
  You can't store a loose document directly on the warehouse floor; you must go inside.

- A Container is a **Filing Cabinet** inside that warehouse. You might have one cabinet 
  labeled 'Invoices-2026' and another labeled 'User-Avatars'. Each cabinet defines its 
  own organization and lock settings (access levels).

- A Blob is an **Individual Document** or folder slipped inside a drawer of that specific 
  filing cabinet. It holds the actual content you want to preserve.
"""

# Q2

"""
Scenario 1 (Raw JSON Payload):
I would use Blob Storage because it is highly optimized for storing raw, semi-structured 
unstructured data efficiently and cheaply without forcing schema validation before reprocessing.

Scenario 2 (50 Million Customer Transactions Table):
I would use a relational database (like Azure SQL) because structured tables requiring 
heavy daily analytical queries, indexing on key fields (date/ID), and high-performance filtering 
belong in a relational database engine.

Scenario 3 (NumPy Arrays for Image Embeddings):
I would use Blob Storage because NumPy arrays are binary files, and Blob Storage is designed 
specifically to serialize and save large binary assets between computing runs economically.
"""

# Q3
from azure.storage.blob import ContainerClient

def list_container(container_client: ContainerClient) -> None:
    """
    Lists and prints the name and size (in bytes) of every blob 
    inside the provided container.
    
    :param container_client: An instantiated Azure ContainerClient object.
    :return: None
    """
    # Iterate through the generator returned by list_blobs()
    for blob in container_client.list_blobs():
        print(f"{blob.name} ({blob.size} bytes)")
        
# Q4
def upload_text(container_client: ContainerClient, blob_name: str, text: str) -> None:
    """
    Encodes a Python string as UTF-8 and uploads it to Azure Blob Storage,
    overwriting any existing blob with the same name.
    
    :param container_client: An instantiated Azure ContainerClient object.
    :param blob_name: The destination path/name of the blob in the container.
    :param text: The raw string content to upload.
    :return: None
    """
    # Convert the Python string into UTF-8 bytes
    data_bytes = text.encode('utf-8')
    
    # Upload the data, explicitly enabling the overwrite flag
    container_client.upload_blob(name=blob_name, data=data_bytes, overwrite=True)